dist: xenial

group: travis_lts

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt/launchers/
    - $HOME/.cache/spark-versions

language: python

python:
  - "3.7"

jdk:
   - openjdk8

matrix:
  include:
    - env: PYSPARK_PIN_THREAD=true SKLEARN_VERSION=0.21.3 SPARK_VERSION=3.0.0-SNAPSHOT
    - env: SKLEARN_VERSION=0.21.3 SPARK_VERSION=2.4.4

before_install:
  - ./bin/download_travis_dependencies.sh

install:
  - pip install joblib==0.14.0 scikit-learn==${SKLEARN_VERSION} nose==1.3.3 pytest;

script:
  - PYSPARK_PYTHON=python SPARK_HOME=$HOME/.cache/spark-versions/spark-${SPARK_VERSION}-bin-hadoop2.7 ./run-tests.sh

