dist: trusty

group: travis_lts

cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt/launchers/
    - $HOME/.cache/spark-versions

language: scala

jdk:
   - oraclejdk8

matrix:
  include:
    - env: PYSPARK_PIN_THREAD=true SKLEARN_VERSION=0.21.3 SPARK_VERSION=3.0.0-SNAPSHOT SPARK_BUILD="spark-${SPARK_VERSION}-bin-hadoop2.7"
    - env: SKLEARN_VERSION=0.21.3 SPARK_VERSION=2.4.4 SPARK_BUILD="spark-${SPARK_VERSION}-bin-hadoop2.7"

before_install:
  - ./bin/download_travis_dependencies.sh

install:
  - pyenv install -f 3.6.3 && pyenv global 3.6.3;
    python3 -m pip install --user joblib==0.14.0 scikit-learn==${SKLEARN_VERSION} nose==1.3.3 pytest;

script:
  - PYSPARK_PYTHON=python3 SPARK_HOME=$HOME/.cache/spark-versions/$SPARK_BUILD ./run-tests.sh

